# Site settings
title:
  Trello Computer Club
baseurl:
  "/computer-club"
url:
  "http://trello.github.io"
twitter_username:
  trello
github_username:
  trello
markdown:
  redcarpet
redcarpet:
  extensions: ["smart", "tables", "strikethrough", "superscript", "footnotes"]
highlighter:
  rouge
safe:
  true
lsi:
  false
permalink:
  /:title
