title:
  Spoke Proof
url:
  "http://hao.codes"
markdown:
  kramdown
highlighter:
  pygments
safe:
  true
lsi:
  false
permalink:
  /:title.html
description:
  "Spoke Proof: Haskell, lenses, C, and everything else"
