# Site settings
title:
  Computer Club
baseurl:
  "/computer-club"
url:
  "http://trello.github.io"
markdown:
  redcarpet
redcarpet:
  extensions: ["smart", "tables", "strikethrough", "superscript", "footnotes"]
highlighter:
  pygments
safe:
  true
lsi:
  false
permalink:
  /:title
description:
  "over the last zero years we've written almost a handful of articles on this site about software development, management, business, and the Internet"
