title:
  Computer Club
url:
  "http://hao.codes"
markdown:
  redcarpet
redcarpet:
  extensions: ["smart", "tables", "strikethrough", "superscript", "footnotes"]
highlighter:
  pygments
safe:
  true
lsi:
  false
permalink:
  /:title
description:
  "over the last zero years Hao Lian has written almost a handful of articles on this site about software development, management, business, and the Internet"
