title:
  Spoke Proof
url:
  "http://hao.codes"
markdown:
  kramdown
highlighter:
  rouge
kramdown:
  syntax_highlighter: rouge
  input: GFM
safe:
  true
lsi:
  false
permalink:
  /:title.html
description:
  "Spoke Proof by Hao Lian"
version:
  1
