title:
  Spoke Proof
url:
  "http://hao.codes"
markdown:
  redcarpet
redcarpet:
  extensions: ["smart", "tables", "strikethrough", "superscript", "footnotes"]
highlighter:
  pygments
safe:
  true
lsi:
  false
permalink:
  /:title.html
description:
  "Spoke Proof: Haskell, lenses, C, and everything else"
