# Site settings
title:
  Trello Computer Club
baseurl:
  "/computer-club"
url:
  "http://trello.github.io"
twitter_username:
  trello
github_username:
  trello
highligher:
  pygments
safe:
  true
lsi:
  false
permalink:
  /:title

# Build settings
markdown: kramdown
